import list map error_handling_module
from test import assert assert_eq

# List passed to function expecting a map
x = try
  map.keys [0 1 2]
  99
catch error
  -1

assert_eq x -1

# Error in functor passed to external function
try
  list.filter [0..10] |x| x + error_in_functor
  assert false
catch error
  x = 0
finally
  x = 42

assert_eq x 42

# Error in function in another module
try
  error_handling_module.error_function()
catch error
  x = 99

assert_eq x 99
